### ISSUE TITLE
Weird artifacts on the surface.

### ISSUE THREAD

**Issue by LyesHammadouche** [MattFerraro/causticsEngineering#10] opened 2021-09-02 07:34 UTC
Hello, 

Wanting to play around with the gravitational caustic project, i tried to run the program on the default image & a picture of mine. In both ARTIFACTS Appeared. So i guess i'ts not ready for acrylic CNC :) . 

![ZBrush_BkSG83E7Fq](https://user-images.githubusercontent.com/89966396/131800382-5f7f2ad4-b8af-4296-9c92-85735543a2e4.jpg)

I Also barely see a height difference, it only appears when i force it trough scaling the depth. It doesnt Not seem as right as shown in Matt heightmap example made a 3D object. 

![ZBrush_nU1ycLv5BR](https://user-images.githubusercontent.com/89966396/131800400-fcc0f831-fe4e-4360-b4cc-f6a90cef0fe3.jpg)

Also appears when the picture is changed : 

![image](https://user-images.githubusercontent.com/89966396/131801135-b7c140d1-a8c6-4595-8967-7cf5a89e6275.png)

that becomes ( and it's turned ). 

![ZBrush_Fgc5KqXnFQ](https://user-images.githubusercontent.com/89966396/131801383-d46efb7f-1287-43c6-acf4-c808747b4389.jpg)

Last but not least, i can't identify wich variable in wich code to change to define the focal plane distance , anybody knows ? ( i am reffering to the Poisson's equation figure 2.8) : 

![image](https://user-images.githubusercontent.com/89966396/131801982-1559ee4f-e744-4fee-b672-bab6cc2d9eab.png)

thank you so much Matt Ferero for sharing your amazing work & thorough explanation. 

Lyes

**Comment by MattFerraro** [comment] 2021-09-03 02:18
Hello Lyes,

What artifacts are you seeing? Can you describe exactly what you expected to see and how it is different from what you are seeing?

The height difference is indeed very small. For a 10cm x 10cm image, the total height variation is about 2.0mm. Are you seeing much less than that? How are you measuring height difference?

Lastly, the value in question is hardcoded [here](https://github.com/MattFerraro/causticsEngineering/blob/main/src/create_mesh.jl#L921). In this line of code, the `1.0` indicates the distance from the object to the image in meters. For me, a distance of `0.2` worked much better than a distance of `1.0` in practice because the shorter focal length makes the lens more powerful, which makes the height variations larger, which makes the pieces easier to manufacture with the limited precision of a homemade CNC router. The smaller that number is bigger your height variations will be.

**Comment by MattFerraro** [comment] 2021-09-03 02:20
You may also be interested in modifying `artifactSize` which is a few lines above. This is also in meters and assumed to be a square.

**Comment by LyesHammadouche** [comment] 2021-09-05 07:28
Hello @MattFerraro , 

Thank you so much for your answer, I will try to modify those two factors and see how it goes if I try to directly use your mesh for 3D carving. 

Artefacts:
What I referred to as being artifices is the horizontal carved lines that I can see through the moiré effects due to the software readings of the surface wireframe. 
I investigated this effect enlarging the scale on the depth axis. And this shows the shapes being enlarged. 

![image](https://user-images.githubusercontent.com/89966396/132119077-f936b186-82c6-46e3-9550-8baa694b2bbe.png)


Delta variations:
The reason for the later scale enlarging was also because when I compared the mesh output given by the cat picture with the picture that you give in your walk through, I found the delta in depth to be inferior to 1 mm while, a rough look at this mesh of yours (assuming the size of the square would be 10 Cm wide) would have a depth around 1 cm to 5 mm. 

Scale & experiments: 

Of course this is only assumption as I didn’t actually test the mesh yet, but i did send this mesh created through your program to be carved in an acrylic slab, it will arrive somewhere around next week. Factory says it will be 80% transparent, so I'll have to do a bit of polish on my side, but previous experiments showed that with a flame, it can be carefully and quickly rendered perfectly transparent with a smooth surface.

I modified the depth scale in a total empirical manner to have it match the depth of the cat picture, I'll see how the focal plane will be affected. 

Further experiences: 

I want to create a sculptural rotating mechanism that will make a L.E.D. pivot around a circle of acrylic slabs. When the light would revolve over an acrylic slab, it would display the ‘hidden’ picture on the surface. I got that idea because I found your first demonstration video amazing when the light caustics gather to form a picture. 

Another test would be to make jewellery pieces with it, and for both tests, I would need to have a focal plane between 10 cm to 20 cm from the source.

![Uploading Brown_Paper_Recycled_Toothy.jpg…]()


: )

**Comment by MattFerraro** [comment] 2021-09-08 02:59
holy shit! great work!

I honestly never expected anyone to take this and run with it. You are the first other person I know of to try and produce an object from this repo!

I never considered what would happen with a circular crop before. I imagine the output image will look pretty good, but the perimeter of the circle won't quite be a perfect circle. There will be some distortion, but I don't think it'll be so bad as to ruin the image.

How on earth did you get such a clear finished product? did you sand and polish or use a blowtorch?

Your idea for a rotating display with moving LED lights sound absolutely phenomenal. I cannot wait to see it!

Instead of paying to have a part manufactured, there is potentially a cheaper way to test: Use [Blender](https://www.blender.org/). Blender is free software that can render high quality images, mostly used for video games and art. Blender's built-in renderers are not physically accurate, but there is a free plugin called [BlendLuxCore](https://luxcorerender.org/download/) which allows you to render physically accurate, ray-traced caustics. I am not very good at using either of these technologies but if you are, or if you know someone who is, or if you have maybe 8 hours to crash course yourself through youtube tutorials, you can use their free software to produce software renderings that validate your 3D meshes.

I wish I could provide more help, but that's about as much as I know and I'm not good enough to provide a working example.

**Comment by MattFerraro** [comment] 2021-09-08 03:01
Regarding the actual artifacts that are the main topic of this bug: I have no idea. I don't see them when I run the code. Hopefully this weekend I can dig in a little more and see what's up. Are you running on an image which is 512x512 pixels square? That's the only resolution I'm confident can work.

**Comment by LyesHammadouche** [comment] 2021-09-08 07:44
I am honored to be able to use your program, I have been fascinated by the subject of architectural caustics for 3 years, when I discovered the 2013 research from Thomas Kiser. Since i only found one swiss company called Rayform that could do it, but they charge a very expensive price for the files : 6000€ for a projection of a 1m diameter lens to a 3m pictures on a 20m distance wall. They're called Rayform. 

Thanks to your work I can make all the sculptures and works I dreamed of. It's so beautiful and poetic to be able to encode information in a medium and reveal it with light. By the way, another application that I will test this weekend will be to 3D print a piece of jewelry to use the surface in reflection rather than in transparency.I also have the idea to make a solar clock that would use this same principle rather than using a shadow. 

Regarding the quality of the finish, I have subcontracted, I am lucky to live in China which allows me to find some skilled workers. I insisted on the importance of the resolution of the finish pass on the depth axis. When I work with acrylic, after polishing I always finish with flame.

For my editing I cropped the image by making a circle, the distortion is ok I'm not looking for anything perfect, thinking about it I think it's even better with grain and artifacts, it allows some distance between the message and the technique.  

Great idea to use Blender, I didn't even think about it, I was using Zbrush and their shaders are not great for this project! While Blender my go to for 3D, i use it quite often, and i didn't know the BlendLuxCore plugin, this looks amazing, i thought that Cycles was already physically accurate but maybe for caustics it get's tricky. 

On more practical level, should i close this Github issue and open a follow up on my project's use of this software, i'm new to GH and i dont want to mess with this git. 

You provided more then enough guidance. I confirm that i'm using a 512x512 picture on square pixels file format.

**Comment by LyesHammadouche** [comment] 2021-09-08 16:47
I am so thrilled by Blender Lux that i couldnt wait any longer to share my late night experiments. (Thanks again for that great tip ! ) 
 I tried the render with the different files i generated for a focal distance of .15 meters.  

I worked with two source files, one is the above Giotto's annonciation the other one is a friends childish drawing.
![cat_posing](https://user-images.githubusercontent.com/89966396/132549010-df458b62-7b48-4a83-b78b-1908efb8369b.jpg)
![josema](https://user-images.githubusercontent.com/89966396/132549161-aa4393bb-3ca8-4d9f-b102-525ef3715b05.jpg)
I converted the second one to black and white and forced a white background on it. 

I tried 3 things : one was to use the acrylic IOR with different sources, the childish drawing on black and white and then inversed, original is on the right : 

![blender_tzTzrTtvXt](https://user-images.githubusercontent.com/89966396/132549438-b01ecadd-2393-4538-a536-013f4b167d77.jpg)

Only the original drawing (without beeing inversed "worked"). I was curious to try inversing 
Upclose it goes like this with and without denoiser.  (couldnt figure out how to deactivate it at first. There is a viewfinder setting and a render one )
![blender_f71le6MjP5](https://user-images.githubusercontent.com/89966396/132549615-c6b4e01f-bb22-45cb-940d-d973f6b04b4c.jpg)
 
![blender_dWFXvK21I0](https://user-images.githubusercontent.com/89966396/132549607-bd55a7a1-2b02-4e24-a9ed-ae65b3a2cf66.jpg)

Then i tried to see if the idea of making a jewel was possible, while using the reflection properties instead of transparency, so i created a mirror material and tried out several distances, and i think that it's doable, so' ill give it a try by 3D printing a 4cm silver pendant in polished silver this weekend. 

![blender_Apj5Dz4W4h](https://user-images.githubusercontent.com/89966396/132549950-fcdc66bc-a901-41cd-8c0d-496e0b0f08a1.jpg)

Last but not least, i tried it with the Giotto picture to try out how changing the focal plane would affect the picture quality : 

![blender_b3yNruAGn9](https://user-images.githubusercontent.com/89966396/132550079-aee85a0b-7744-4262-a066-1704c978685c.jpg)
![blender_XsGgXASCHr](https://user-images.githubusercontent.com/89966396/132550085-2145fd32-4cf4-4661-acd3-058df6d055ad.jpg)
![blender_gnQjTEtx40](https://user-images.githubusercontent.com/89966396/132550089-1ac4ead6-7134-482f-8614-5076c49a7dfd.jpg)

I'm so happy beeing able to preview those works, it will save money, but i can even preview the effect on my solidworks prototype etc. It's crazy. 

Also i can see that what i qualified as articats are now diagonal "leaks" of light, i think there is beauty in it, and i really don't know where it comes from.   :)

**Comment by MattFerraro** [comment] 2021-09-10 04:28
I found a fixed a whole bunch of small issues with the solver. Can you try again with the latest version of the code?

You'll still have to hardcode your own [artifact size and focal length](https://github.com/MattFerraro/causticsEngineering/blob/main/src/create_mesh.jl#L925-L926) and also your own [image name](https://github.com/MattFerraro/causticsEngineering/blob/main/run.jl#L6). I do not see the wavy lines and I'd be curious to know if you still seem them with the version of the code now on the main branch.

**Comment by LyesHammadouche** [comment] 2021-09-11 15:25
Hi @MattFerraro 

I'am having a late night try on the new program, though i'm failing to make it work, i usually use the command terminal to do so, but it gives me this error message: 

![image](https://user-images.githubusercontent.com/89966396/132952721-3443fb41-dffa-43b0-bca0-fbc43fcaa9a5.png)

And when i try to run it with visual run time it goes like this : 

![image](https://user-images.githubusercontent.com/89966396/132952787-e6eea7bc-5384-4898-b728-e28fd35a90d7.png)


Beeing fairly mediocre at coding i have no clue to what's happening, maybe a Julia package that is required, that i don't have, nor do i know how to add them there. The previous version of the code is still working though, so i made the jewel design for a caustic reflection test : dimensions are : 
40x40x4.5mm, Focal is set to 0.15, and Artifacts is unchanged.  

![ZBrush_XBmgskTReh](https://user-images.githubusercontent.com/89966396/132952898-168eed56-e709-409a-b96d-2b45eb6f518e.jpg)
![ZBrush_FbRB8K288c](https://user-images.githubusercontent.com/89966396/132952901-ffe95a59-fef5-496f-b640-04ea4dea9dae.jpg)

**Comment by LyesHammadouche** [comment] 2021-09-13 07:59
Hello Matt, 

I found a work around for my incompetence :3. My lazy brain found out that you only edited the Src folder codes in the git, so i replaced those ones in the previous version of my "working file", and it worked like a charm. 

I have to say that i'm amazed as all the artifacts have disappeared and now it displays a beautifull triangulated mesh, that i can even see trough moiree effect. 

![ZBrush_d3jGsonmG9](https://user-images.githubusercontent.com/89966396/133043089-6654c84a-1e5c-4426-8227-233a0433e146.jpg)

It also is way thicker therefore easier to manipulate as a mesh, and i can clearly see the thickness variation progress trough the geometry's surface.

![ZBrush_OmN3fCTx98](https://user-images.githubusercontent.com/89966396/133043218-3518043d-4775-4092-8184-d3c69a558c17.jpg)


So i went on with different experiments to see how different parameters would affect the caustic picture. 

- I changed the distance from the lens to the cube surface and rendered with luxblend;  The scale of the cubes are 10x10cm, and they are at various focal of 10 cm, 15cm and 20cm away from the surface. 

![blender_4APsscbINc](https://user-images.githubusercontent.com/89966396/133043290-f77fdeb3-963c-457b-83eb-05da17a6337e.jpg)

![blender_irAthCwtah](https://user-images.githubusercontent.com/89966396/133043452-0efd523f-7f27-4807-86ca-a95d89fb6cd4.jpg)

The contrast is stronger when the glass is closest to the coded focal, but still it feels like the variation is not that big. I have yet to see the result with the carved Giotto picture in acrylic that will arrive withtin the week. 

Those were the processed files. And the mesh export dimensions. 

![firefox_EOILRpoWfK](https://user-images.githubusercontent.com/89966396/133043645-9dcb5a45-768e-414e-ac85-1ac6a4b369fb.jpg)
![ZBrush_qVbfw6DtFJ](https://user-images.githubusercontent.com/89966396/133043739-8de9a054-9a36-4702-9ac2-e5f8cd65411f.jpg)

- I changed the thickness of the mesh to see if it had any impact on the resulting picture; 



![ZBrush_mEb4sFQQW9](https://user-images.githubusercontent.com/89966396/133043852-f7a4cedb-77c9-4789-9298-153a2c5d892c.jpg)
![ZBrush_S9OupgqwoL](https://user-images.githubusercontent.com/89966396/133043861-e3b45529-d251-4ad3-b30b-cc4252d2b48e.jpg)
![blender_CxGtCCLHM3](https://user-images.githubusercontent.com/89966396/133043863-99cbff4c-7f98-4ae3-af15-8b3327a6d6d9.jpg)
![blender_0LzvTutFjJ](https://user-images.githubusercontent.com/89966396/133043867-c47f23c4-7479-441e-8c04-e78e4886e036.jpg)

Btw, i discovered that Luxblend is GPU rendering compatible wich makes it all way faster to compute. You have to go in the render settings and enable the Path tracing GPU on the viewport option. 

- I also changed the original picture contrast and converted it to black and white. 

![Photoshop_0B2gjtp7AW](https://user-images.githubusercontent.com/89966396/133044103-65e4790f-9416-4fbf-98f9-d82237d23c45.jpg)
![blender_4q4uFvhyqR](https://user-images.githubusercontent.com/89966396/133044187-02b13cdd-9a36-41fa-bc70-4c21c6bba979.jpg)
![Photoshop_IlUNR53DI9](https://user-images.githubusercontent.com/89966396/133044194-551e6b7d-86c3-4d31-a52c-153c22be7f11.jpg)
![explorer_VYxGYo3bXL](https://user-images.githubusercontent.com/89966396/133044196-8611af9c-5374-4108-be58-1ddd0d0ab587.jpg)

 Doing such, i found out that the contrast was more crisp, and that gave me the following idea : 

- I inverted the black & white picture to see what the effect would be. 

![Photoshop_FDKruxYc24](https://user-images.githubusercontent.com/89966396/133044390-059894ec-e45c-4d70-af66-f8542f6eeb30.jpg)

**And to get a sharp image i had to get the lens 7cm close to the surface, while it is coded for a 0.2m distance. Wich makes no sense to me :) .** 

![blender_KfzsDuKTdr](https://user-images.githubusercontent.com/89966396/133044412-a7709283-c304-45b4-89ab-956021157152.jpg)
![blender_9szYFJM7KZ](https://user-images.githubusercontent.com/89966396/133044687-960636c6-d17e-4478-97f3-ffe2941fdfeb.jpg)

And i'm not even sure i get the correct image, i'm so close to the view that the lens is getting in the way. I could decide not to render the lens but that would count as sorcery , or cheating. 

In the meanwhile i received the first failed attempt to make the acrylic while using my logo. I think here, that it's crucial to have a black on white logo instead of the opposite, as i tried previously with the Adam creation picture (hands) it has an impact on the focal length that is not related to the set focal in the program.   
![image](https://user-images.githubusercontent.com/89966396/133045706-356fef28-e8ae-49c8-bf0b-a4f4748147cd.png)
![image](https://user-images.githubusercontent.com/89966396/133045739-e5f58133-c8d5-4c14-b652-f16d5f4b8078.png)

We can see the toolpath, quite good accuracy, i can be further polished eventually. 



And here is a preview of the carved Giotto Annunciation lens. 


https://user-images.githubusercontent.com/89966396/133045917-cd14556a-1b30-421f-909d-c5b2416d6285.mp4


I'am having so much fun with your code , it's crazy good!

**Comment by LyesHammadouche** [comment] 2021-09-25 10:41
Hello @MattFerraro 

Here is a head's up on my latest try, i'm very happy with the outcomes, it had to go through much, and it is so interesting.  I was more confortable handwritting, i hope it's not too much of a challenge to read me. 
You definitly got rid of the artifcats. 

Hope my feedback can help and is not bothering you. It's a fantastic process to me ! 



https://user-images.githubusercontent.com/89966396/134768547-d3c7263c-58e6-4fc0-a6ef-0483f29bad4a.mp4



Even though the picture is full of artifcats ( using the previous version of the code), i love the way the caustics comes together to form it in a beautifull transition, I guess it's due to the high contrast of the image used in this one. 



https://user-images.githubusercontent.com/89966396/134768488-1d3163c7-c99b-4e4e-9a68-b2990bad1a7b.mp4




![process and outcomes](https://user-images.githubusercontent.com/89966396/134768474-6eacb64d-451f-4e0e-9484-acb4b1041d56.jpg)

**Comment by MattFerraro** [comment] 2021-09-29 02:49
wow! incredible work! I'm so impressed with what you've been able to achieve!

**Comment by MattFerraro** [comment] 2021-10-05 01:41
I'm going to close this issue because I believe I've resolved the root cause of the artifacts. But please create a new issue if you see new problems, and please show me as you make more things! You've inspired me to try some circular pieces as well.

**Closed by MattFerraro** 2021-10-05 01:41 UTC
